In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(a[0])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b[0][2])

[1 2 3]
1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


In [2]:
a=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

(3, 3)
2
int32
4
9


In [3]:
print(np.zeros((3,4)))
print(np.ones((3,4),dtype=np.int32))
print(np.eye(3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
x=np.ones(5,dtype=np.int64)
print(x)

[1 1 1 1 1]


In [5]:
print(np.arange(5))
print(np.arange(1,6))
print(np.arange(1,10,2))

[0 1 2 3 4]
[1 2 3 4 5]
[1 3 5 7 9]


In [6]:
print(np.linspace(0,10,100))

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [7]:
arr=np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [8]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(np.concatenate((x,y), axis=1))
print(np.concatenate((x,y), axis=0))

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [9]:
print(np.vstack((x,y)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [10]:
print(np.hstack((x,y)))

[[1 2 5 6]
 [3 4 7 8]]


In [11]:
a=np.arange(12)
print(a)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [12]:
print(a.reshape(3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
print(a.reshape(6,-1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [14]:
a=np.arange(30).reshape(-1,10)
print(a)
a1,a2=np.split(a,[3],axis=1)
print(a1)
print(a2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]]
[[ 3  4  5  6  7  8  9]
 [13 14 15 16 17 18 19]
 [23 24 25 26 27 28 29]]


In [15]:
a=np.array([1,2,3,4,5,6])
print(a)
print(a.shape)
a1=a[np.newaxis,:]
print(a1)
print(a1.shape)
a2=a[:,np.newaxis]
print(a2)
print(a2.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3 4 5 6]]
(1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [16]:
b=np.expand_dims(a,axis=1)
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [17]:
ages=np.array([18,19,25,30,28])
print(ages[1:3])
print(ages[:2])
y=ages>20
print(y)
print(ages[ages>20])

[19 25]
[18 19]
[False False  True  True  True]
[25 30 28]


In [18]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,2])
a[0,0]=12
print(a)

3
[[12  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [19]:
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data[0:2,1:3])
print(data[0])
print(data[1,1:3])

[[2 3]
 [5 6]]
[1 2 3]
[5 6]


In [20]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[0,:]
print(b)
b[0]=99
print(b)
print(a)
b1=a
print(b1)
b2=a.copy()
print(b2)
a[0,0]=100
print(a)
print(b1)
print(b2)

[1 2 3 4]
[99  2  3  4]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
a1=np.array([[1,2],[3,4],[5,6]])
a2=np.array([[1,1],[1,1],[1,1]])
r=a1+a2
print(r)

[[2 3]
 [4 5]
 [6 7]]


In [22]:
a=np.array([0,1,2,3])
print(a**2)

[0 1 4 9]


In [23]:
a=np.array([0,9,21,3])
print(a<10)

[ True  True False  True]


In [24]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.sum())
print(a.max())
print(a.min())

45
9
1


In [25]:
scores=np.array([[99,93,60],[98,82,93],[93,65,81],[78,82,81]])
print(scores)
print(scores.mean(axis=0))
print(scores.mean(axis=1))

[[99 93 60]
 [98 82 93]
 [93 65 81]
 [78 82 81]]
[92.   80.5  78.75]
[84.         91.         79.66666667 80.33333333]


In [26]:
m=np.array([1,2,3])
r=m*1.6
print(r)

[1.6 3.2 4.8]


In [27]:
a1=np.array([[1,2],[3,4],[5,6]])
a2=np.array([[2,2],[2,2],[2,2]])
r=a1*a2
print(r)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [28]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[2,2],[2,2],[2,2]])
r=a1@a2
print(r)

[[12 12]
 [30 30]
 [48 48]]


In [29]:
a=np.array([0,1,2,3])
print(10*np.sin(a))

[0.         8.41470985 9.09297427 1.41120008]


In [30]:
np.random.seed(1000)
print(np.random.rand(5))
print(np.random.rand(5,3))

[0.65358959 0.11500694 0.95028286 0.4821914  0.87247454]
[[0.21233268 0.04070962 0.39719446]
 [0.2331322  0.84174072 0.20708234]
 [0.74246953 0.39215413 0.18225652]
 [0.74353941 0.06958208 0.8853372 ]
 [0.9526444  0.93114343 0.41543095]]


In [31]:
a,b=10,20
print((b-a)*np.random.rand(5)+a)

[10.28981659 19.82027485 13.39637684 17.06687194 13.61877068]


In [32]:
print(np.random.randint(1,7,size=10))

[3 6 3 5 1 5 5 4 2 4]


In [33]:
print(np.random.randn(5))
print(np.random.randn(5,4))

[-0.08988248 -0.14974264  0.4055338  -0.75133127  0.93131848]
[[-0.24745023 -0.27072883 -1.27939856 -1.07900875]
 [-0.08796666  2.05225999 -1.23931612  1.10970741]
 [-1.15768513  0.09870641 -1.4651006  -1.75193341]
 [ 1.96503337 -0.34876717 -0.44128298 -0.3947238 ]
 [-0.81437341  0.16256696 -1.57323867 -1.78792302]]


In [34]:
mu,sigma=0,0.1
print(np.random.normal(mu,sigma,5))

[ 0.19093792  0.06282858 -0.18764819 -0.0321585  -0.06866277]


In [35]:
a=np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])
print(a)
u=np.unique(a)
print(u)
v,il=np.unique(a,return_index=True)
print(v)
print(a)
print(il)
v,cl=np.unique(a,return_counts=True)
print(a)
print(v)
print(cl)

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]
[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]
[11 12 13 14 15 16 17 18 19 20]
[3 2 2 2 1 1 1 1 1 1]


In [36]:
arr=np.array([[1,2],[3,4],[5,6]])
print(arr)
print(arr.T)
print(arr.transpose())

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


In [37]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
import numpy as np
import pandas as pd
x=pd.read_csv('countries.csv',header=0).values
print(x)
x=pd.read_csv('countries.csv',usecols=['country','capital'],header=0).values
print(x)

[['KR' 'Korea' 98480 'Seoul' 48422644]
 ['US' 'USA' 9629091 'Washington' 310232863]
 ['JP' 'Japan' 377835 'Tokyo' 127288000]
 ['CN' 'China' 9596960 'Beijing' 1330044000]
 ['RU' 'Russia' 17100000 'Moscow' 140702000]]
[['Korea' 'Seoul']
 ['USA' 'Washington']
 ['Japan' 'Tokyo']
 ['China' 'Beijing']
 ['Russia' 'Moscow']]


In [39]:
a=np.arange(100,116,1).reshape(4,4)
df=pd.DataFrame(a)
print(df)
df.to_csv('pd.csv')

     0    1    2    3
0  100  101  102  103
1  104  105  106  107
2  108  109  110  111
3  112  113  114  115
